//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public int FK_homeTeam { get; set; }
        public int FK_awayTeam { get; set; }
        public int awayTeamScore { get; set; }
        public int homeTeamScore { get; set; }
        public int numberOfSpectators { get; set; }
        public int FK_winningTeam { get; set; }
    
        public virtual Team Team { get; set; }
        public virtual Team Team1 { get; set; }
        public virtual Team Team2 { get; set; }
    }
}
